### PR TITLE
Added support for az storagaccount and loading of external modules 

### PR DESCRIPTION
**Pull request by WithHolm**
Added support for  az storagaccount, both as a parameter and as a piped element. 
TableName still has to be defined.

Also added Requiremodules to psd1, with reference to the correct version as specified by you and with the correct module GUID

### CODE REVIEW

**Comment by paulomarquesc** [comment]
Hi WithHolm,

For item 1 in your description, what would be the use-case for directly supporting it? I provided a code sample in the isuse  (https://github.com/paulomarquesc/AzureRmStorageTable/issues/44) you opened.
 
For item 2, that sounds good.

Regards

Paulo

**Comment by WithHolm** [comment]
1# This also means that you dont need [requires in the psm1](https://github.com/paulomarquesc/AzureRmStorageTable/blob/master/AzureRmStorageTableCoreHelper.psm1#L12)

2# You are probably right, and it might feel like a feature creep, but then again, if you already have the storageaccount context for usage to other SA services, why would one need to make another call to Azure to get the same context, and have to define storageaccount and resourcegroup again (Adding ~1,3 sec instead of ~300 MS)?
``` Powershell
$SA = get-azStorageAccount  -ResourceGroupName 'SomeRG' -StorageAccountName 'StorAacc'
$Blob = $sa|Get-AzStorageContainer -Name "SomeContainer"
$Queue = $sa|Get-AzStorageQueue -Name "Somequeue"
#Current with storagetable az function
$CTable1 = ($sa|Get-AzStorageTable -Name 'Sometable').cloudtable
#Suggested 
$CTable2 = $sa|Get-AzTableTable -Name 'SomeOtherTable'
```

In Addition, i might also send a new pull request for using connection string aswell, for usage with Az Functions [Like this](https://github.com/WithHolm/With.FakeProfiles/blob/98fade3719acf9db95ba6704204f0fc334145f1e/AzFunctions/ProcessFace/run.ps1#L36),

**Comment by kaiaschulz** [comment]
Downloaded the repository as .zip-file and tried to import it as module in Azure.

**Got the following failure:**
_Error importing the module AzureRmStorageTable-master. Import failed with the following error: Orchestrator.Shared.AsyncModuleImport.ModuleImportException: Cannot import the module of name AzureRmStorageTable-master, as the module structure was invalid._

Any hints for successfully adding this module to Azure?

**Comment by WithHolm** [comment]
Hi,
I dont know if this works (reply all in mail). please let me know if you
received this, kaia.

take a look at the readme
https://github.com/paulomarquesc/AzureRmStorageTable/blob/master/docs/README.md#installationsource-code
for
instructions of how to install the module :)

--Philip

**Comment by paulomarquesc** [comment]
@PaulCheng , can you please follow up on this?

**Pull request closed without merging**
